### ISSUE TITLE
geom.coords is an attribute, not a function. Should be geom.coordinates()

### ISSUE THREAD

**Issue by vingman** [QChASM/SEQCROW#2]
Traceback (most recent call last):
  File "/home/deo/.local/share/ChimeraX/1.1/site-packages/SEQCROW/tools/normal_modes.py", line 449, in show_anim
    Xf = geom.coords() + dX
TypeError: 'numpy.ndarray' object is not callable

TypeError: 'numpy.ndarray' object is not callable

File "/home/deo/.local/share/ChimeraX/1.1/site-packages/SEQCROW/tools/normal_modes.py", line 449, in show_anim
Xf = geom.coords() + dX

**Comment by ajs99778** [comment]
This has been fixed on the Toolshed version and (I think) on the GitHub versions. Make sure you've got SEQCROW version 0.22a0 or 0.23 by running `toolshed list installed` on the ChimeraX command line.
